### ISSUE TITLE
Possible Unused Argument

### ISSUE THREAD

**Issue by erisco** [qlova/tech#1]
https://github.com/qlova/tech/blob/8010f9e308d790248528430c7dcb1ea4dcbaf70e/sum/sum.go#L188

Is the val argument necessary? It seems to be unused.

**Comment by Splizard** [comment]
It may not be helpful any longer, as type inference has improved in Go 1.21, it  only exists to enable the type parameters to be omitted.

**Comment by erisco** [comment]
Hello Splizard,

I am not sure it can infer. I was just using `sum.Case[Sum](x, func(y T) { ... })` so `x` seemed redundant.

The version which does not infer from an argument does not seem definable outside the module. In my case, I don't have an advantage of inferring from an argument versus just supplying the type.

Anyways, you're saying this is by design, so I'll close the issue. Thanks for the response!
